# Generated by Django 3.2.9 on 2021-11-28 13:38

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Page Component',
                'verbose_name_plural': 'Page Components',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
            },
        ),
        migrations.CreateModel(
            name='SectionTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('sub_header', models.CharField(blank=True, max_length=200)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.page')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.pagesection')),
            ],
            options={
                'verbose_name': 'Section Text Content',
                'verbose_name_plural': 'Section Text Contents',
            },
        ),
        migrations.CreateModel(
            name='ComponentTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('sub_header', models.CharField(blank=True, max_length=200)),
                ('header', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60, null=True)),
                ('slug', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pages.pagecomponent')),
            ],
            options={
                'verbose_name': 'Component Text Content',
                'verbose_name_plural': 'Component Text Contents',
            },
        ),
    ]
