# Generated by Django 3.2.9 on 2021-11-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('replied', models.BooleanField(default=False)),
                ('reply', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Messages',
                'verbose_name_plural': 'Contact Messages',
            },
        ),
    ]
